### PR TITLE
Added Theme Changer

### PR DESCRIPTION
**Pull request by akshayrai14**
Added a Theme Changing Button which toggles between "Light" and "Dark" Theme.

The Theme Change Button is available on top right corner.

Dark Mode looks like this (original):
image

Light Mode looks like:
image

### CODE REVIEW

**Comment by mistermantas** [comment]
Thanks for the active contributions! However the button should probably have an icon and not have the same style as the primary button. Looks a little bit strange at the moment. I like feathericons.com's dark mode / light mode button more, for instance. I can merge if you change it around. I also recommend adding a three bar / hamburger menu and putting the github/contact/about links there if you can manage the extra effort to do that. The dark mode switch would fit perfectly under a hamburger menu. I want the UI to be as minimalist and simple as possible.

**Comment by mistermantas** [comment]
Another thing I recommend checking out is media prefers-color-scheme which automatically switches themes based on a CSS class. Not required, you might find it interesting. I also added another issue at #7

**Comment by akshayrai14** [comment]
Dark Mode:
image

Light Mode:
image

**Comment by mistermantas** [comment]
Thanks!

**Comment by akshayrai14** [comment]
If you could merge my pull request then it would be very helpful for me as i have to complete hacktoberfest .

**Comment by mistermantas** [comment]
I added the hacktoberfest-accepted label and it should count as an accepted pr, show up as waiting.

**Pull request merged**
